[package]
name = "sha1sum"
version = "0.9.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
